/**
 * API Pago Facil
 * API de Pago Fácil
 *
 * The version of the OpenAPI document: 2.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DataLoginResponse model module.
 * @module model/DataLoginResponse
 * @version 2.1.4
 */
class DataLoginResponse {
    /**
     * Constructs a new <code>DataLoginResponse</code>.
     * Respuesta de login
     * @alias module:model/DataLoginResponse
     */
    constructor() { 
        
        DataLoginResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DataLoginResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DataLoginResponse} obj Optional instance to populate.
     * @return {module:model/DataLoginResponse} The populated <code>DataLoginResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DataLoginResponse();

            if (data.hasOwnProperty('access_token_jwt')) {
                obj['access_token_jwt'] = ApiClient.convertToType(data['access_token_jwt'], 'String');
            }
            if (data.hasOwnProperty('expires_in')) {
                obj['expires_in'] = ApiClient.convertToType(data['expires_in'], 'Number');
            }
            if (data.hasOwnProperty('token_type')) {
                obj['token_type'] = ApiClient.convertToType(data['token_type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * JWT (JSON Web Token) que se usará para las llamadas del API
 * @member {String} access_token_jwt
 */
DataLoginResponse.prototype['access_token_jwt'] = undefined;

/**
 * Tiempo por el cual el JWT será valido
 * @member {Number} expires_in
 */
DataLoginResponse.prototype['expires_in'] = undefined;

/**
 * Tipo de Token
 * @member {String} token_type
 */
DataLoginResponse.prototype['token_type'] = undefined;






export default DataLoginResponse;

