/**
 * API Pago Facil
 * API de Pago Fácil
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FutureRemittances model module.
 * @module model/FutureRemittances
 * @version 2.1.0
 */
class FutureRemittances {
    /**
     * Constructs a new <code>FutureRemittances</code>.
     * Monto y transacciones de abonos futuros
     * @alias module:model/FutureRemittances
     */
    constructor() { 
        
        FutureRemittances.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FutureRemittances</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FutureRemittances} obj Optional instance to populate.
     * @return {module:model/FutureRemittances} The populated <code>FutureRemittances</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FutureRemittances();

            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('remittances')) {
                obj['remittances'] = ApiClient.convertToType(data['remittances'], [Object]);
            }
        }
        return obj;
    }


}

/**
 * Monto de la transacción
 * @member {Number} total
 */
FutureRemittances.prototype['total'] = undefined;

/**
 * @member {Array.<Object>} remittances
 */
FutureRemittances.prototype['remittances'] = undefined;






export default FutureRemittances;

