/**
 * API Pago Facil
 * API de Pago Fácil
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse2008Types model module.
 * @module model/InlineResponse2008Types
 * @version 2.1.0
 */
class InlineResponse2008Types {
    /**
     * Constructs a new <code>InlineResponse2008Types</code>.
     * @alias module:model/InlineResponse2008Types
     */
    constructor() { 
        
        InlineResponse2008Types.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse2008Types</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse2008Types} obj Optional instance to populate.
     * @return {module:model/InlineResponse2008Types} The populated <code>InlineResponse2008Types</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2008Types();

            if (data.hasOwnProperty('codigo')) {
                obj['codigo'] = ApiClient.convertToType(data['codigo'], 'String');
            }
            if (data.hasOwnProperty('nombre')) {
                obj['nombre'] = ApiClient.convertToType(data['nombre'], 'String');
            }
            if (data.hasOwnProperty('descripcion')) {
                obj['descripcion'] = ApiClient.convertToType(data['descripcion'], 'String');
            }
            if (data.hasOwnProperty('url_imagen')) {
                obj['url_imagen'] = ApiClient.convertToType(data['url_imagen'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} codigo
 */
InlineResponse2008Types.prototype['codigo'] = undefined;

/**
 * @member {String} nombre
 */
InlineResponse2008Types.prototype['nombre'] = undefined;

/**
 * @member {String} descripcion
 */
InlineResponse2008Types.prototype['descripcion'] = undefined;

/**
 * @member {String} url_imagen
 */
InlineResponse2008Types.prototype['url_imagen'] = undefined;






export default InlineResponse2008Types;

