/**
 * API Pago Facil
 * API de Pago Fácil
 *
 * The version of the OpenAPI document: 2.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse500 model module.
 * @module model/InlineResponse500
 * @version 2.1.4
 */
class InlineResponse500 {
    /**
     * Constructs a new <code>InlineResponse500</code>.
     * @alias module:model/InlineResponse500
     */
    constructor() { 
        
        InlineResponse500.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse500</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse500} obj Optional instance to populate.
     * @return {module:model/InlineResponse500} The populated <code>InlineResponse500</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse500();

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ApiClient.convertToType(data['errors'], ['String']);
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {String} message
 */
InlineResponse500.prototype['message'] = undefined;

/**
 * @member {Array.<String>} errors
 */
InlineResponse500.prototype['errors'] = undefined;

/**
 * @member {Object} data
 */
InlineResponse500.prototype['data'] = undefined;






export default InlineResponse500;

