/**
 * API Pago Facil
 * API de Pago Fácil
 *
 * The version of the OpenAPI document: 2.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FutureRemittances from './FutureRemittances';
import RemittanceByDate from './RemittanceByDate';

/**
 * The InlineResponse200Data model module.
 * @module model/InlineResponse200Data
 * @version 2.1.4
 */
class InlineResponse200Data {
    /**
     * Constructs a new <code>InlineResponse200Data</code>.
     * @alias module:model/InlineResponse200Data
     */
    constructor() { 
        
        InlineResponse200Data.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse200Data</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse200Data} obj Optional instance to populate.
     * @return {module:model/InlineResponse200Data} The populated <code>InlineResponse200Data</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse200Data();

            if (data.hasOwnProperty('availableBalance')) {
                obj['availableBalance'] = ApiClient.convertToType(data['availableBalance'], 'Number');
            }
            if (data.hasOwnProperty('remittanceByDate')) {
                obj['remittanceByDate'] = RemittanceByDate.constructFromObject(data['remittanceByDate']);
            }
            if (data.hasOwnProperty('futureRemittances')) {
                obj['futureRemittances'] = FutureRemittances.constructFromObject(data['futureRemittances']);
            }
        }
        return obj;
    }


}

/**
 * Monto de la transacción
 * @member {Number} availableBalance
 */
InlineResponse200Data.prototype['availableBalance'] = undefined;

/**
 * @member {module:model/RemittanceByDate} remittanceByDate
 */
InlineResponse200Data.prototype['remittanceByDate'] = undefined;

/**
 * @member {module:model/FutureRemittances} futureRemittances
 */
InlineResponse200Data.prototype['futureRemittances'] = undefined;






export default InlineResponse200Data;

