/**
 * API Pago Facil
 * API de Pago Fácil
 *
 * The version of the OpenAPI document: 2.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse2001DataNullifications model module.
 * @module model/InlineResponse2001DataNullifications
 * @version 2.1.4
 */
class InlineResponse2001DataNullifications {
    /**
     * Constructs a new <code>InlineResponse2001DataNullifications</code>.
     * @alias module:model/InlineResponse2001DataNullifications
     */
    constructor() { 
        
        InlineResponse2001DataNullifications.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse2001DataNullifications</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse2001DataNullifications} obj Optional instance to populate.
     * @return {module:model/InlineResponse2001DataNullifications} The populated <code>InlineResponse2001DataNullifications</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2001DataNullifications();

            if (data.hasOwnProperty('tipo')) {
                obj['tipo'] = ApiClient.convertToType(data['tipo'], 'String');
            }
            if (data.hasOwnProperty('montoAnulado')) {
                obj['montoAnulado'] = ApiClient.convertToType(data['montoAnulado'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Number');
            }
            if (data.hasOwnProperty('dateTime')) {
                obj['dateTime'] = ApiClient.convertToType(data['dateTime'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} tipo
 */
InlineResponse2001DataNullifications.prototype['tipo'] = undefined;

/**
 * @member {Number} montoAnulado
 */
InlineResponse2001DataNullifications.prototype['montoAnulado'] = undefined;

/**
 * @member {String} status
 */
InlineResponse2001DataNullifications.prototype['status'] = undefined;

/**
 * Timestamp de unix en segundos
 * @member {Number} timestamp
 */
InlineResponse2001DataNullifications.prototype['timestamp'] = undefined;

/**
 * @member {Date} dateTime
 */
InlineResponse2001DataNullifications.prototype['dateTime'] = undefined;






export default InlineResponse2001DataNullifications;

