/**
 * API Pago Facil
 * API de Pago Fácil
 *
 * The version of the OpenAPI document: 2.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InlineResponse2001DataDocument from './InlineResponse2001DataDocument';

/**
 * The InlineResponse2001DataItems model module.
 * @module model/InlineResponse2001DataItems
 * @version 2.1.4
 */
class InlineResponse2001DataItems {
    /**
     * Constructs a new <code>InlineResponse2001DataItems</code>.
     * @alias module:model/InlineResponse2001DataItems
     */
    constructor() { 
        
        InlineResponse2001DataItems.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse2001DataItems</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse2001DataItems} obj Optional instance to populate.
     * @return {module:model/InlineResponse2001DataItems} The populated <code>InlineResponse2001DataItems</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2001DataItems();

            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('cost')) {
                obj['cost'] = ApiClient.convertToType(data['cost'], 'Number');
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('idTrx')) {
                obj['idTrx'] = ApiClient.convertToType(data['idTrx'], 'Number');
            }
            if (data.hasOwnProperty('order_id_tienda')) {
                obj['order_id_tienda'] = ApiClient.convertToType(data['order_id_tienda'], 'String');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Number');
            }
            if (data.hasOwnProperty('dateTimeCreatedAt')) {
                obj['dateTimeCreatedAt'] = ApiClient.convertToType(data['dateTimeCreatedAt'], 'Date');
            }
            if (data.hasOwnProperty('isTotalNullified')) {
                obj['isTotalNullified'] = ApiClient.convertToType(data['isTotalNullified'], 'Boolean');
            }
            if (data.hasOwnProperty('isParcialNullified')) {
                obj['isParcialNullified'] = ApiClient.convertToType(data['isParcialNullified'], 'Boolean');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('document')) {
                obj['document'] = InlineResponse2001DataDocument.constructFromObject(data['document']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} amount
 */
InlineResponse2001DataItems.prototype['amount'] = undefined;

/**
 * @member {Number} cost
 */
InlineResponse2001DataItems.prototype['cost'] = undefined;

/**
 * @member {Number} total
 */
InlineResponse2001DataItems.prototype['total'] = undefined;

/**
 * @member {Number} idTrx
 */
InlineResponse2001DataItems.prototype['idTrx'] = undefined;

/**
 * @member {String} order_id_tienda
 */
InlineResponse2001DataItems.prototype['order_id_tienda'] = undefined;

/**
 * Timestamp de unix en milisegundos
 * @member {Number} createdAt
 */
InlineResponse2001DataItems.prototype['createdAt'] = undefined;

/**
 * @member {Date} dateTimeCreatedAt
 */
InlineResponse2001DataItems.prototype['dateTimeCreatedAt'] = undefined;

/**
 * @member {Boolean} isTotalNullified
 */
InlineResponse2001DataItems.prototype['isTotalNullified'] = undefined;

/**
 * @member {Boolean} isParcialNullified
 */
InlineResponse2001DataItems.prototype['isParcialNullified'] = undefined;

/**
 * @member {String} currency
 */
InlineResponse2001DataItems.prototype['currency'] = undefined;

/**
 * @member {module:model/InlineResponse2001DataDocument} document
 */
InlineResponse2001DataItems.prototype['document'] = undefined;






export default InlineResponse2001DataItems;

