/**
 * API Pago Facil
 * API de Pago Fácil
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject4 model module.
 * @module model/InlineObject4
 * @version 2.1.0
 */
class InlineObject4 {
    /**
     * Constructs a new <code>InlineObject4</code>.
     * @alias module:model/InlineObject4
     * @param url {String} La url que recibirá un POST para notificaciones
     * @param method {module:model/InlineObject4.MethodEnum} Método HTTP a ser usado durante el callback
     * @param webhook {module:model/InlineObject4.WebhookEnum} Tipo de evento del webhook
     * @param idUser {String} Id del usuario que quiere crear el webhook
     */
    constructor(url, method, webhook, idUser) { 
        
        InlineObject4.initialize(this, url, method, webhook, idUser);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, url, method, webhook, idUser) { 
        obj['url'] = url;
        obj['method'] = method;
        obj['webhook'] = webhook;
        obj['idUser'] = idUser;
    }

    /**
     * Constructs a <code>InlineObject4</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject4} obj Optional instance to populate.
     * @return {module:model/InlineObject4} The populated <code>InlineObject4</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject4();

            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('method')) {
                obj['method'] = ApiClient.convertToType(data['method'], 'String');
            }
            if (data.hasOwnProperty('webhook')) {
                obj['webhook'] = ApiClient.convertToType(data['webhook'], 'String');
            }
            if (data.hasOwnProperty('idUser')) {
                obj['idUser'] = ApiClient.convertToType(data['idUser'], 'String');
            }
        }
        return obj;
    }


}

/**
 * La url que recibirá un POST para notificaciones
 * @member {String} url
 */
InlineObject4.prototype['url'] = undefined;

/**
 * Método HTTP a ser usado durante el callback
 * @member {module:model/InlineObject4.MethodEnum} method
 */
InlineObject4.prototype['method'] = undefined;

/**
 * Tipo de evento del webhook
 * @member {module:model/InlineObject4.WebhookEnum} webhook
 */
InlineObject4.prototype['webhook'] = undefined;

/**
 * Id del usuario que quiere crear el webhook
 * @member {String} idUser
 */
InlineObject4.prototype['idUser'] = undefined;





/**
 * Allowed values for the <code>method</code> property.
 * @enum {String}
 * @readonly
 */
InlineObject4['MethodEnum'] = {

    /**
     * value: "POST"
     * @const
     */
    "POST": "POST",

    /**
     * value: "GET"
     * @const
     */
    "GET": "GET"
};


/**
 * Allowed values for the <code>webhook</code> property.
 * @enum {String}
 * @readonly
 */
InlineObject4['WebhookEnum'] = {

    /**
     * value: "remittances"
     * @const
     */
    "remittances": "remittances"
};



export default InlineObject4;

