/**
 * API Pago Facil
 * API de Pago Fácil
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InlineResponse2002BodyData from './InlineResponse2002BodyData';

/**
 * The InlineResponse2002Body model module.
 * @module model/InlineResponse2002Body
 * @version 2.1.0
 */
class InlineResponse2002Body {
    /**
     * Constructs a new <code>InlineResponse2002Body</code>.
     * @alias module:model/InlineResponse2002Body
     */
    constructor() { 
        
        InlineResponse2002Body.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse2002Body</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse2002Body} obj Optional instance to populate.
     * @return {module:model/InlineResponse2002Body} The populated <code>InlineResponse2002Body</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2002Body();

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = InlineResponse2002BodyData.constructFromObject(data['data']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} message
 */
InlineResponse2002Body.prototype['message'] = undefined;

/**
 * @member {module:model/InlineResponse2002BodyData} data
 */
InlineResponse2002Body.prototype['data'] = undefined;






export default InlineResponse2002Body;

