/**
 * API Pago Facil
 * API de Pago Fácil
 *
 * The version of the OpenAPI document: 2.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse2001DataDocument model module.
 * @module model/InlineResponse2001DataDocument
 * @version 2.1.4
 */
class InlineResponse2001DataDocument {
    /**
     * Constructs a new <code>InlineResponse2001DataDocument</code>.
     * @alias module:model/InlineResponse2001DataDocument
     */
    constructor() { 
        
        InlineResponse2001DataDocument.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse2001DataDocument</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse2001DataDocument} obj Optional instance to populate.
     * @return {module:model/InlineResponse2001DataDocument} The populated <code>InlineResponse2001DataDocument</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2001DataDocument();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
InlineResponse2001DataDocument.prototype['id'] = undefined;

/**
 * @member {String} type
 */
InlineResponse2001DataDocument.prototype['type'] = undefined;






export default InlineResponse2001DataDocument;

