/**
 * API Pago Facil
 * API de Pago Fácil
 *
 * The version of the OpenAPI document: 2.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class NullificationType.
* @enum {}
* @readonly
*/
export default class NullificationType {
    
        /**
         * value: "total"
         * @const
         */
        "total" = "total";

    
        /**
         * value: "parcial"
         * @const
         */
        "parcial" = "parcial";

    

    /**
    * Returns a <code>NullificationType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/NullificationType} The enum <code>NullificationType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

