/**
 * API Pago Facil
 * API de Pago Fácil
 *
 * The version of the OpenAPI document: 2.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RemittanceByDate model module.
 * @module model/RemittanceByDate
 * @version 2.1.4
 */
class RemittanceByDate {
    /**
     * Constructs a new <code>RemittanceByDate</code>.
     * Monto del abono relacionado a las transacciones que se debieron pagar el dia indicado y dichas transacciones
     * @alias module:model/RemittanceByDate
     */
    constructor() { 
        
        RemittanceByDate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RemittanceByDate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RemittanceByDate} obj Optional instance to populate.
     * @return {module:model/RemittanceByDate} The populated <code>RemittanceByDate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RemittanceByDate();

            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('trxs')) {
                obj['trxs'] = ApiClient.convertToType(data['trxs'], [Object]);
            }
        }
        return obj;
    }


}

/**
 * Monto de la transacción
 * @member {Number} total
 */
RemittanceByDate.prototype['total'] = undefined;

/**
 * Objeto de transacciones
 * @member {Array.<Object>} trxs
 */
RemittanceByDate.prototype['trxs'] = undefined;






export default RemittanceByDate;

