/**
 * API Pago Facil
 * API de Pago Fácil
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Shippment model module.
 * @module model/Shippment
 * @version 2.1.0
 */
class Shippment {
    /**
     * Constructs a new <code>Shippment</code>.
     * Datos de despacho
     * @alias module:model/Shippment
     * @param contactName {String} Nombre de contacto
     * @param phone {String} Número de teléfono
     * @param region {String} Región
     * @param city {String} Ciudad
     * @param address {String} Dirección
     * @param municipality {String} Municipio
     * @param rut {String} Rut
     */
    constructor(contactName, phone, region, city, address, municipality, rut) { 
        
        Shippment.initialize(this, contactName, phone, region, city, address, municipality, rut);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, contactName, phone, region, city, address, municipality, rut) { 
        obj['contact_name'] = contactName;
        obj['phone'] = phone;
        obj['region'] = region;
        obj['city'] = city;
        obj['address'] = address;
        obj['municipality'] = municipality;
        obj['rut'] = rut;
    }

    /**
     * Constructs a <code>Shippment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Shippment} obj Optional instance to populate.
     * @return {module:model/Shippment} The populated <code>Shippment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Shippment();

            if (data.hasOwnProperty('contact_name')) {
                obj['contact_name'] = ApiClient.convertToType(data['contact_name'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('region')) {
                obj['region'] = ApiClient.convertToType(data['region'], 'String');
            }
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('municipality')) {
                obj['municipality'] = ApiClient.convertToType(data['municipality'], 'String');
            }
            if (data.hasOwnProperty('rut')) {
                obj['rut'] = ApiClient.convertToType(data['rut'], 'String');
            }
            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
            if (data.hasOwnProperty('zip')) {
                obj['zip'] = ApiClient.convertToType(data['zip'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Nombre de contacto
 * @member {String} contact_name
 */
Shippment.prototype['contact_name'] = undefined;

/**
 * Número de teléfono
 * @member {String} phone
 */
Shippment.prototype['phone'] = undefined;

/**
 * Región
 * @member {String} region
 */
Shippment.prototype['region'] = undefined;

/**
 * Ciudad
 * @member {String} city
 */
Shippment.prototype['city'] = undefined;

/**
 * Dirección
 * @member {String} address
 */
Shippment.prototype['address'] = undefined;

/**
 * Municipio
 * @member {String} municipality
 */
Shippment.prototype['municipality'] = undefined;

/**
 * Rut
 * @member {String} rut
 */
Shippment.prototype['rut'] = undefined;

/**
 * País en donde se encuentra la tienda (dos caracteres)
 * @member {String} country
 */
Shippment.prototype['country'] = undefined;

/**
 * Código postal
 * @member {String} zip
 */
Shippment.prototype['zip'] = undefined;






export default Shippment;

