/**
 * API Pago Facil
 * API de Pago Fácil
 *
 * The version of the OpenAPI document: 2.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The XCustomerEmail model module.
 * @module model/XCustomerEmail
 * @version 2.1.4
 */
class XCustomerEmail {
    /**
     * Constructs a new <code>XCustomerEmail</code>.
     * Email
     * @alias module:model/XCustomerEmail
     */
    constructor() { 
        
        XCustomerEmail.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>XCustomerEmail</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/XCustomerEmail} obj Optional instance to populate.
     * @return {module:model/XCustomerEmail} The populated <code>XCustomerEmail</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new XCustomerEmail();

        }
        return obj;
    }


}






export default XCustomerEmail;

