/**
 * API Pago Facil
 * API de Pago Fácil
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import InlineResponse2001 from '../model/InlineResponse2001';
import InlineResponse400 from '../model/InlineResponse400';
import InlineResponse500 from '../model/InlineResponse500';

/**
* Remittances service.
* @module api/RemittancesApi
* @version 2.1.0
*/
export default class RemittancesApi {

    /**
    * Constructs a new RemittancesApi. 
    * @alias module:api/RemittancesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the remittancesConciliationGet operation.
     * @callback module:api/RemittancesApi~remittancesConciliationGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2001} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Permite obtener la conciliación de los abonos
     * @param {String} email Email a consultar
     * @param {Date} _date Fecha de consulta año-mes-dia <br> Ej: 2019-12-31
     * @param {module:api/RemittancesApi~remittancesConciliationGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2001}
     */
    remittancesConciliationGet(email, _date, callback) {
      let postBody = null;
      // verify the required parameter 'email' is set
      if (email === undefined || email === null) {
        throw new Error("Missing the required parameter 'email' when calling remittancesConciliationGet");
      }
      // verify the required parameter '_date' is set
      if (_date === undefined || _date === null) {
        throw new Error("Missing the required parameter '_date' when calling remittancesConciliationGet");
      }

      let pathParams = {
      };
      let queryParams = {
        'email': email,
        'date': _date
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['JWTToken'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse2001;
      return this.apiClient.callApi(
        '/remittances/conciliation', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
