/**
 * API Pago Facil
 * API de Pago Fácil
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiPagoFacil);
  }
}(this, function(expect, ApiPagoFacil) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiPagoFacil.InlineObject1();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineObject1', function() {
    it('should create an instance of InlineObject1', function() {
      // uncomment below and update the code to test InlineObject1
      //var instane = new ApiPagoFacil.InlineObject1();
      //expect(instance).to.be.a(ApiPagoFacil.InlineObject1);
    });

    it('should have the property xAccountId (base name: "x_account_id")', function() {
      // uncomment below and update the code to test the property xAccountId
      //var instane = new ApiPagoFacil.InlineObject1();
      //expect(instance).to.be();
    });

    it('should have the property xAmount (base name: "x_amount")', function() {
      // uncomment below and update the code to test the property xAmount
      //var instane = new ApiPagoFacil.InlineObject1();
      //expect(instance).to.be();
    });

    it('should have the property xCurrency (base name: "x_currency")', function() {
      // uncomment below and update the code to test the property xCurrency
      //var instane = new ApiPagoFacil.InlineObject1();
      //expect(instance).to.be();
    });

    it('should have the property xReference (base name: "x_reference")', function() {
      // uncomment below and update the code to test the property xReference
      //var instane = new ApiPagoFacil.InlineObject1();
      //expect(instance).to.be();
    });

    it('should have the property xCustomerEmail (base name: "x_customer_email")', function() {
      // uncomment below and update the code to test the property xCustomerEmail
      //var instane = new ApiPagoFacil.InlineObject1();
      //expect(instance).to.be();
    });

    it('should have the property xUrlComplete (base name: "x_url_complete")', function() {
      // uncomment below and update the code to test the property xUrlComplete
      //var instane = new ApiPagoFacil.InlineObject1();
      //expect(instance).to.be();
    });

    it('should have the property xUrlCancel (base name: "x_url_cancel")', function() {
      // uncomment below and update the code to test the property xUrlCancel
      //var instane = new ApiPagoFacil.InlineObject1();
      //expect(instance).to.be();
    });

    it('should have the property xUrlCallback (base name: "x_url_callback")', function() {
      // uncomment below and update the code to test the property xUrlCallback
      //var instane = new ApiPagoFacil.InlineObject1();
      //expect(instance).to.be();
    });

    it('should have the property xSignature (base name: "x_signature")', function() {
      // uncomment below and update the code to test the property xSignature
      //var instane = new ApiPagoFacil.InlineObject1();
      //expect(instance).to.be();
    });

    it('should have the property xShopCountry (base name: "x_shop_country")', function() {
      // uncomment below and update the code to test the property xShopCountry
      //var instane = new ApiPagoFacil.InlineObject1();
      //expect(instance).to.be();
    });

    it('should have the property xSessionId (base name: "x_session_id")', function() {
      // uncomment below and update the code to test the property xSessionId
      //var instane = new ApiPagoFacil.InlineObject1();
      //expect(instance).to.be();
    });

    it('should have the property xProducts (base name: "x_products")', function() {
      // uncomment below and update the code to test the property xProducts
      //var instane = new ApiPagoFacil.InlineObject1();
      //expect(instance).to.be();
    });

    it('should have the property xBillingDetails (base name: "x_billing_details")', function() {
      // uncomment below and update the code to test the property xBillingDetails
      //var instane = new ApiPagoFacil.InlineObject1();
      //expect(instance).to.be();
    });

    it('should have the property xShippment (base name: "x_shippment")', function() {
      // uncomment below and update the code to test the property xShippment
      //var instane = new ApiPagoFacil.InlineObject1();
      //expect(instance).to.be();
    });

    it('should have the property xDocument (base name: "x_document")', function() {
      // uncomment below and update the code to test the property xDocument
      //var instane = new ApiPagoFacil.InlineObject1();
      //expect(instance).to.be();
    });

  });

}));
