/**
 * API Pago Facil
 * API de Pago Fácil
 *
 * The version of the OpenAPI document: 2.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiPagoFacil);
  }
}(this, function(expect, ApiPagoFacil) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiPagoFacil.InlineResponse2008Types();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse2008Types', function() {
    it('should create an instance of InlineResponse2008Types', function() {
      // uncomment below and update the code to test InlineResponse2008Types
      //var instane = new ApiPagoFacil.InlineResponse2008Types();
      //expect(instance).to.be.a(ApiPagoFacil.InlineResponse2008Types);
    });

    it('should have the property codigo (base name: "codigo")', function() {
      // uncomment below and update the code to test the property codigo
      //var instane = new ApiPagoFacil.InlineResponse2008Types();
      //expect(instance).to.be();
    });

    it('should have the property nombre (base name: "nombre")', function() {
      // uncomment below and update the code to test the property nombre
      //var instane = new ApiPagoFacil.InlineResponse2008Types();
      //expect(instance).to.be();
    });

    it('should have the property descripcion (base name: "descripcion")', function() {
      // uncomment below and update the code to test the property descripcion
      //var instane = new ApiPagoFacil.InlineResponse2008Types();
      //expect(instance).to.be();
    });

    it('should have the property urlImagen (base name: "url_imagen")', function() {
      // uncomment below and update the code to test the property urlImagen
      //var instane = new ApiPagoFacil.InlineResponse2008Types();
      //expect(instance).to.be();
    });

  });

}));
