/**
 * API Pago Facil
 * API de Pago Fácil
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiPagoFacil);
  }
}(this, function(expect, ApiPagoFacil) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiPagoFacil.TrxsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TrxsApi', function() {
    describe('trxsIdGet', function() {
      it('should call trxsIdGet successfully', function(done) {
        //uncomment below and update the code to test trxsIdGet
        //instance.trxsIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('trxsIdTrxNullificationGet', function() {
      it('should call trxsIdTrxNullificationGet successfully', function(done) {
        //uncomment below and update the code to test trxsIdTrxNullificationGet
        //instance.trxsIdTrxNullificationGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('trxsIdTrxNullificationPost', function() {
      it('should call trxsIdTrxNullificationPost successfully', function(done) {
        //uncomment below and update the code to test trxsIdTrxNullificationPost
        //instance.trxsIdTrxNullificationPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('trxsIdTrxNullificationStatusGet', function() {
      it('should call trxsIdTrxNullificationStatusGet successfully', function(done) {
        //uncomment below and update the code to test trxsIdTrxNullificationStatusGet
        //instance.trxsIdTrxNullificationStatusGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('trxsPost', function() {
      it('should call trxsPost successfully', function(done) {
        //uncomment below and update the code to test trxsPost
        //instance.trxsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
