/**
 * API Pago Facil
 * API de Pago Fácil
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BillingDetails model module.
 * @module model/BillingDetails
 * @version 2.1.0
 */
class BillingDetails {
    /**
     * Constructs a new <code>BillingDetails</code>.
     * Datos de facturación
     * @alias module:model/BillingDetails
     * @param rut {String} Rut
     * @param city {String} Ciudad
     * @param company {String} Empresa
     * @param municipality {String} Municipio
     * @param activity {String} Giro de la emmpresa
     * @param address {String} Dirección
     * @param country {String} País en donde se encuentra la tienda (dos caracteres)
     */
    constructor(rut, city, company, municipality, activity, address, country) { 
        
        BillingDetails.initialize(this, rut, city, company, municipality, activity, address, country);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, rut, city, company, municipality, activity, address, country) { 
        obj['rut'] = rut;
        obj['city'] = city;
        obj['company'] = company;
        obj['municipality'] = municipality;
        obj['activity'] = activity;
        obj['address'] = address;
        obj['country'] = country;
    }

    /**
     * Constructs a <code>BillingDetails</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BillingDetails} obj Optional instance to populate.
     * @return {module:model/BillingDetails} The populated <code>BillingDetails</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BillingDetails();

            if (data.hasOwnProperty('rut')) {
                obj['rut'] = ApiClient.convertToType(data['rut'], 'String');
            }
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('company')) {
                obj['company'] = ApiClient.convertToType(data['company'], 'String');
            }
            if (data.hasOwnProperty('municipality')) {
                obj['municipality'] = ApiClient.convertToType(data['municipality'], 'String');
            }
            if (data.hasOwnProperty('activity')) {
                obj['activity'] = ApiClient.convertToType(data['activity'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Rut
 * @member {String} rut
 */
BillingDetails.prototype['rut'] = undefined;

/**
 * Ciudad
 * @member {String} city
 */
BillingDetails.prototype['city'] = undefined;

/**
 * Empresa
 * @member {String} company
 */
BillingDetails.prototype['company'] = undefined;

/**
 * Municipio
 * @member {String} municipality
 */
BillingDetails.prototype['municipality'] = undefined;

/**
 * Giro de la emmpresa
 * @member {String} activity
 */
BillingDetails.prototype['activity'] = undefined;

/**
 * Dirección
 * @member {String} address
 */
BillingDetails.prototype['address'] = undefined;

/**
 * País en donde se encuentra la tienda (dos caracteres)
 * @member {String} country
 */
BillingDetails.prototype['country'] = undefined;






export default BillingDetails;

