/**
 * API Pago Facil
 * API de Pago Fácil
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse2002BodyDataPayUrl model module.
 * @module model/InlineResponse2002BodyDataPayUrl
 * @version 2.1.0
 */
class InlineResponse2002BodyDataPayUrl {
    /**
     * Constructs a new <code>InlineResponse2002BodyDataPayUrl</code>.
     * @alias module:model/InlineResponse2002BodyDataPayUrl
     */
    constructor() { 
        
        InlineResponse2002BodyDataPayUrl.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse2002BodyDataPayUrl</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse2002BodyDataPayUrl} obj Optional instance to populate.
     * @return {module:model/InlineResponse2002BodyDataPayUrl} The populated <code>InlineResponse2002BodyDataPayUrl</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2002BodyDataPayUrl();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
InlineResponse2002BodyDataPayUrl.prototype['name'] = undefined;

/**
 * @member {String} url
 */
InlineResponse2002BodyDataPayUrl.prototype['url'] = undefined;






export default InlineResponse2002BodyDataPayUrl;

