/**
 * API Pago Facil
 * API de Pago Fácil
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InlineResponse2002BodyDataPayUrl from './InlineResponse2002BodyDataPayUrl';

/**
 * The InlineResponse2002BodyData model module.
 * @module model/InlineResponse2002BodyData
 * @version 2.1.0
 */
class InlineResponse2002BodyData {
    /**
     * Constructs a new <code>InlineResponse2002BodyData</code>.
     * @alias module:model/InlineResponse2002BodyData
     */
    constructor() { 
        
        InlineResponse2002BodyData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse2002BodyData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse2002BodyData} obj Optional instance to populate.
     * @return {module:model/InlineResponse2002BodyData} The populated <code>InlineResponse2002BodyData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2002BodyData();

            if (data.hasOwnProperty('idTrx')) {
                obj['idTrx'] = ApiClient.convertToType(data['idTrx'], 'Number');
            }
            if (data.hasOwnProperty('payUrl')) {
                obj['payUrl'] = ApiClient.convertToType(data['payUrl'], [InlineResponse2002BodyDataPayUrl]);
            }
        }
        return obj;
    }


}

/**
 * id de la transaccion
 * @member {Number} idTrx
 */
InlineResponse2002BodyData.prototype['idTrx'] = undefined;

/**
 * Opciones diferentes de pago. <br> Para mostrar todas las opciones utilizar 'gateway'. <br> Para ir directamente a un metodo de pago, utilizar las demás disponibles
 * @member {Array.<module:model/InlineResponse2002BodyDataPayUrl>} payUrl
 */
InlineResponse2002BodyData.prototype['payUrl'] = undefined;






export default InlineResponse2002BodyData;

