/**
 * API Pago Facil
 * API de Pago Fácil
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse2009 model module.
 * @module model/InlineResponse2009
 * @version 2.1.0
 */
class InlineResponse2009 {
    /**
     * Constructs a new <code>InlineResponse2009</code>.
     * @alias module:model/InlineResponse2009
     * @param id {Number} Identificador del usuario
     * @param idAuth0 {String} Identificador del usuario
     * @param username {String} Nombre del usuario
     * @param email {String} Email del usuario
     * @param status {Number} Define el estado del usuario en inscripcion
     * @param bloqueo {Boolean} Define si el usuario esta bloqueado
     * @param createdAt {String} Fecha de creacion del usuario
     */
    constructor(id, idAuth0, username, email, status, bloqueo, createdAt) { 
        
        InlineResponse2009.initialize(this, id, idAuth0, username, email, status, bloqueo, createdAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, idAuth0, username, email, status, bloqueo, createdAt) { 
        obj['id'] = id;
        obj['idAuth0'] = idAuth0;
        obj['username'] = username;
        obj['email'] = email;
        obj['status'] = status;
        obj['bloqueo'] = bloqueo;
        obj['createdAt'] = createdAt;
    }

    /**
     * Constructs a <code>InlineResponse2009</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse2009} obj Optional instance to populate.
     * @return {module:model/InlineResponse2009} The populated <code>InlineResponse2009</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2009();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('idAuth0')) {
                obj['idAuth0'] = ApiClient.convertToType(data['idAuth0'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
            if (data.hasOwnProperty('bloqueo')) {
                obj['bloqueo'] = ApiClient.convertToType(data['bloqueo'], 'Boolean');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Identificador del usuario
 * @member {Number} id
 */
InlineResponse2009.prototype['id'] = undefined;

/**
 * Identificador del usuario
 * @member {String} idAuth0
 */
InlineResponse2009.prototype['idAuth0'] = undefined;

/**
 * Nombre del usuario
 * @member {String} username
 */
InlineResponse2009.prototype['username'] = undefined;

/**
 * Email del usuario
 * @member {String} email
 */
InlineResponse2009.prototype['email'] = undefined;

/**
 * Define el estado del usuario en inscripcion
 * @member {Number} status
 */
InlineResponse2009.prototype['status'] = undefined;

/**
 * Define si el usuario esta bloqueado
 * @member {Boolean} bloqueo
 */
InlineResponse2009.prototype['bloqueo'] = undefined;

/**
 * Fecha de creacion del usuario
 * @member {String} createdAt
 */
InlineResponse2009.prototype['createdAt'] = undefined;






export default InlineResponse2009;

